"""Migracion inicial

Revision ID: 2ece490ac0bc
Revises:
Create Date: 2025-09-17 15:42:29.711635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ece490ac0bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore
    sa.Column('tipo_seguro', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consulta')
    # ### end Alembic commands ###
