"""init

Revision ID: 38102328b943
Revises:
Create Date: 2025-09-22 14:17:21.867362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38102328b943'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afiliado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IdError', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Resultado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('TipoDocumento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('NroDocumento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ApePaterno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ApeMaterno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('FecAfiliacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('EESS', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('DescEESS', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('EESSUbigeo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('DescEESSUbigeo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Regimen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('TipoSeguro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('DescTipoSeguro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Contrato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('FecCaducidad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Estado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Tabla', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IdNumReg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Genero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('FecNacimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IdUbigeo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Disa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('TipoFormato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('NroContrato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Correlativo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IdPlan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IdGrupoPoblacional', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('MsgConfidencial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_afiliado_NroDocumento'), 'afiliado', ['NroDocumento'], unique=False)
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('es_local', sa.Boolean(), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consulta_numero_documento'), 'consulta', ['numero_documento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consulta_numero_documento'), table_name='consulta')
    op.drop_table('consulta')
    op.drop_index(op.f('ix_afiliado_NroDocumento'), table_name='afiliado')
    op.drop_table('afiliado')
    # ### end Alembic commands ###
