"""Afiliado

Revision ID: ee86976468c3
Revises:
Create Date: 2025-09-19 21:54:35.589794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee86976468c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afiliado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IdError', sa.Integer(), nullable=True),
    sa.Column('Resultado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('TipoDocumento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('NroDocumento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ApePaterno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ApeMaterno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('FecAfiliacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('EESS', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('DescEESS', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('EESSUbigeo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('DescEESSUbigeo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Regimen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('TipoSeguro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('DescTipoSeguro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Contrato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('FecCaducidad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Estado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Tabla', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IdNumReg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Genero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('FecNacimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IdUbigeo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Disa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('TipoFormato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('NroContrato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Correlativo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IdPlan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IdGrupoPoblacional', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('MsgConfidencial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ServerError', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afiliado')
    # ### end Alembic commands ###
